# Generated by Django 3.2.3 on 2024-09-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20240924_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='recipes.Recipe', verbose_name='Избранное'),
        ),
    ]
