# Generated by Django 3.2.3 on 2024-10-09 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20240930_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecomposition',
            options={'verbose_name': 'Состав рецепта', 'verbose_name_plural': 'Состав рецепта'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(max_length=32, verbose_name='Короткая ссылка'),
        ),
        migrations.AlterField(
            model_name='recipecomposition',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipecomposition',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='all_recipes', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipecomposition',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='subscribtions',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
        migrations.AlterField(
            model_name='subscribtions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
